version: '3'

services:
  text-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.huggingface:/root/.huggingface  # Mount Hugging Face credentials
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
